# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 111e89469cf1d39e91af54d5b4f8ea23d27fe7a269463d86c5848077ee0e3586fd17b18539ba3d47b2636f7e42896e7a4c788af2c9bf3eec970fed3b4b606253

test:
  secret_key_base: 9d59374be3e4e186ff37c56b0335e0da068722eb7831d35038eed7d0a4580d065703c8bfc4e6f16e18381f258b7922ecbafcd475b2b358a6138144712138e0d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
